#!/usr/bin/env perl
use Dzpl
    name => 'Package-Pkg',
    version => '0.0013',
    author => 'Robert Krimen <robertkrimen@gmail.com>',
    license => 'Perl5',
    copyright => 'Robert Krimen',
    require => q/
        Sub::Install
        Class::MOP

        [Test]
        Test::Most
    /;
;

{ plugin '@ROKR' }
