#!/usr/bin/env perl
use Dzpl
    name => 'Package-Pkg',
    version => '0.0016_2',
    author => 'Robert Krimen <robertkrimen@gmail.com>',
    license => 'Perl5',
    copyright => 'Robert Krimen',
    require => q/
        Mouse
        Sub::Install
        Try::Tiny

        [Test]
        Test::Most
    /;
;

{ plugin '@ROKR' }
